drym-org/symex.el

- symex.el
Dash 2.18.0 now subsumes `dash-functional`.
See https://github.com/magnars/dash.el/blob/master/NEWS.md#from-217-to-218
> Replace deprecated dash-functional dependency

- .github/workflows/melpazoid.yml
The melpazoid workflow is currently failing https://github.com/countvajhula/symex.el/runs/4296416541?check_suite_focus=true#step:5:48 
I believe this is the correct repo name.
> Correct repo name for melpazoid runner

- symex-primitives.el
Clojure has a short [deref reader macro](https://clojure.org/reference/reader#_deref) that is just syntax sugar. When used on a symbol (`@a-ref`) symex.el behaves as expected. However, use on an expression doesn't behave like how I would expect.
(This was initially made as a PR [here](https://github.com/countvajhula/symex.el/pull/34), apologies but I made that off `master` and couldn't work out a way to change the head branch in GH's PR workflow)
```
(do |@(function-returning-a-ref)
(another-symex))
```
`j` →
```
(do |@(function-returning-a-ref)
(another-symex))
```
```
(do @(|function-returning-a-ref)
(another-symex))
```
`f` →
```
(do @(function-returning-a-ref)
|(another-symex))
```
```
(do @(|function-returning-a-ref)
(another-symex))
```
> Add symex--special-left-p case for Clojure(script) deref reader macro

- README.rst
- symex-custom.el
- symex-interface-common-lisp.el
Closes out #43. The only public facing changes are the addition of `symex-common-lisp-backend`. This defaults to `slime` but users can optionally set it to `sly`.
I tried to do some fancy things to reduce code duplication and the nested checks on this variable, but it didn't fit the project style. I don't think it will be a problem since these runtime checks should be `jit`d away.
I didn't see a place in the docs that says `symex supports the following lisps: ...` so I was unsure where to state:
```
Symex can use Sly as a backend for Common Lisp as opposed to Slime. To do so set symex-common-lisp-backend, 
for example you might have the following use-package call (for Doom emacs):
(use-package! symex
:config
(symex-initialize)
(setq symex-common-lisp-backend 'sly)
(map! :after evil
:map …
```
> common-lisp: add sly backend

- symex-primitives.el
Handle more special cases of list forms for movement/navigation. Tested on:
```
()
(+ 2 3)
'(+ 2 3)
'()
#'(+ 2 3)
#'()
`(+ 2 3)
`()
#`(+ 2 3)
#`()
#(1 2 3)
#()
,(+ 2 3)
,()
#,(+ 2 3)
#,()
,@(+ 2 3)
#,@(+ 2 3)
#,@()
,@()
@(1 2 3)
@()
```
One thing to give more thought to down the line is that the primitive Lisp APIs (e.g. Emacs, paredit) don't consider the above to be symexes. That's why they need to be handled as special cases. But doing it on a one-off basis means that only motions/navigations handle them correctly, and for instance transformations like emit and capture don't, and there is no unity in the handling of these cases.
A better way to do it might be to extend the primitives layer to recognize these forms properly, and rewrite the primitive transformations (e.g. emit and …
> Handle more special list forms

- DSL-Docs.rst
- symex-data.el
- symex-dsl.el
- symex-evaluator.el
- symex-interop.el
- symex-misc.el
- symex-primitives-lisp.el
- symex-primitives.el
- symex-transformations.el
- symex-traversals.el
- symex-ts.el
- symex-utils.el
- symex.el
This fixes the leap branch feature in tree-sitter languages, and also includes other improvements.
For leap branch, there were three main issues:
1. In Lisp, the location of the point/cursor uniquely determines both the height (from root) as well as the index (position along current branch). With tree-sitter languages a point location could correspond to more than one hierarchy level (e.g. in `|date = None`). There are some cases (e.g. when a traversal fails) when we need to return to a particular place in the tree (e.g. the node prior to attempting the traversal). In such cases, it was just using `(goto-char original-position)` and then `(symex-select-nearest)` but this would lose any height information.
2. In Lisp, the "root" node is specific to each tree in the buffer, i.e. each …
> Symex ts fix leap branch

- symex-ts.el
In a javascript file like this one:
```
window.BENCHMARK_DATA = {
"lastUpdate": 1658432364487,
"repoUrl": "https://github.com/countvajhula/qi",
}
```
([link to actual file](https://github.com/countvajhula/qi/blob/gh-pages/benchmarks/data.js))
... going "up" towards root while one level below it was causing it to hang.
The reason seems to be that there is a parent node without siblings encountered before the root and that was breaking an assumption somewhere. This PR changes the `symex-ts--at-tree-root-p` check to be consistent with the check for siblings used in actual movements, to fix the issue.
(**Note**: There is another issue in the same file where going down from root to a child node seems to skip a level in some cases. I plan to investigate that further but if I don't get to it …
> Handle an edge case where going down to root would hang

- symex-misc.el
- symex-primitives-lisp.el
- symex-primitives.el
- symex-ts.el
- symex-ui.el
- symex.el
The Symex master branch contains an optional "highlight" feature that uses Emacs regions to highlight the current expression. This is not a great way to do it since regions have existing connotations that interfere with their ability to play the pure UI role of highlighting. For instance, Evil considers an active region to mean "Visual mode". Thus, using highlighting causes existing features like `e`valuate to work in unexpected ways.
The tree-sitter branch introduces an overlay for highlighting the currently selected expression. This is the right way to do it and it doesn't suffer from the problems associated with using regions. The present PR promotes the overlay used for tree-sitter code to the UI level (instead of the primitive tree-sitter level) so that it works for both tree-sitter …
> Generalize overlay for use in Lisp too

- symex-transformations-lisp.el
- symex-transformations-ts.el
- symex-transformations.el
- symex-ts.el
- symex-utils-ts.el
I have started work on implementing the transformations in `symex-transformations.el` with tree sitter.
As with `symex-primitives` I have started moving the existing transformations to a new `symex-transformations-lisp.el` module and I have created a new `symex-transformations-ts.el` module for the new implementations. Once a transformation is implemented, I modify the appropriate function in `symex-transformations.el` to dispatch to the correct implementation based on the value of `tree-sitter-mode`.
This is a work-in-progress! Only a few transformations have been implemented so far (see the list below). The purpose of this PR is therefore to track this work until the point at which it is deemed complete enough to merge to `symex-ts-integration`.
Here are the transformations that I …
> Tree sitter: transformation support

- dev/dev-utils.el
- symex-ts.el
There was still some leftover overlay code in the ts module which was being used by the hydra used for development. I've moved that over to the dev module.
> Move ts-specific overlay to dev module for use in the hydra

- symex-misc.el
- symex-traversals.el
There are often times when we want to jump to the neighboring tree. The current way to do that is to keep leaping/soaring until you reach the next tree. This PR makes "soar" specifically jump to the neighboring tree and not stay within the current tree.
More detail: currently, leap and soar are identical except that leap won't cross to other trees, while soar will. This was done mainly because in some cases if you "leap" you may find yourself in a totally different part of the code (in another tree) and that's usually not what you want. So "leap" encodes the common expectation that you want to stay in the current tree. "Soar" allows you to explicitly say that you're willing to go to another tree.
But this distinction between leap and soar is perhaps too subtle, and so soar isn't as useful …
> Soar across trees

- symex-interface-clojure.el
Cider already has a pretty printing function ( `cider-pprint-eval-last-sexp`). Use this in `symex-eval-pretty-clojure` rather than the standard eval function.
(**Why**: The freely released, copyright-free work in this repository represents an investment in a better way of doing things called _attribution-based economics_. Attribution-based economics is based on the simple idea that we gain more by giving more, not by holding on to things that, truly, we could only create because we, in our turn, received from others. As it turns out, an economic system based on attribution -- where those who give more are more empowered -- is significantly more efficient than capitalism while also being stable and fair (_unlike_ capitalism, on both counts), giving it transformative power to elevate the …
> call cider-pprint-eval-last-sexp to pretty print clojure

- DSL-Docs.rst
- dev/dev-utils.el
- symex-custom.el
- symex-data.el
- symex-dsl.el
- symex-evaluator.el
- symex-evil.el
- symex-hydra.el
- symex-interface-clojure.el
- symex-interop.el
- symex-misc.el
- symex-primitives-lisp.el
- symex-primitives.el
- symex-transformations-lisp.el
- symex-transformations-ts.el
- symex-transformations.el
- symex-traversals.el
- symex-ts.el
- symex-ui.el
- symex-utils-ts.el
- symex-utils.el
- symex.el
Use tree-sitter for non-lisps.
✨ See the [Kanban Board](https://github.com/users/countvajhula/projects/1/views/1). 📒
**Older completed items**:
> Add support for non-Lisp languages by using tree-sitter

- symex-interface-common-lisp.el
Closes #88
Call `sly-mrepl` instead of the deprecated `sly-repl` in `symex-repl-common-lisp`.
(**Why**: The freely released, copyright-free work in this repository represents an investment in a better way of doing things called _attribution-based economics_. Attribution-based economics is based on the simple idea that we gain more by giving more, not by holding on to things that, truly, we could only create because we, in our turn, received from others. As it turns out, an economic system based on attribution -- where those who give more are more empowered -- is significantly more efficient than capitalism while also being stable and fair (_unlike_ capitalism, on both counts), giving it transformative power to elevate the human condition and address the problems that face us today along …
> Fix #88: call sly-mrepl instead of sly-repl in symex-repl-common-lisp

- symex-evil.el
- symex-transformations-lisp.el
- symex-transformations-ts.el
- symex-transformations.el
This adds a couple of macros for defining symex commands. These macros handle the boilerplate of reindenting after execution, etc. and minimize the use of advice for such things, and could also implicitly include other common functionality like evil-repeat (dot `.`) support which currently requires a separate registration step. In general these macros represent a better abstraction of a command than using functions with ad hoc and inconsistently used set up and tear down code, and should allow us to integrate more easily with other tools like tree-edit. See [this ticket](https://github.com/users/countvajhula/projects/1/views/1?pane=issue&itemId=12134124) for a full description.
**Bugs remaining**:
(**Why**: The freely released, copyright-free work in this repository represents an …
> Macros for defining symex commands

- DSL-Docs.rst
- Makefile
- README.rst
- symex-misc.el
- symex-primitives-lisp.el
- symex-transformations-lisp.el
- symex-transformations.el
- symex.el
Trim dependencies to minimize package footprint and also prepare for decomposing the package (#26 ), making it/them more portable and lean.
(**Why**: The freely released, copyright-free work in this repository represents an investment in a better way of doing things called _attribution-based economics_. Attribution-based economics is based on the simple idea that we gain more by giving more, not by holding on to things that, truly, we could only create because we, in our turn, received from others. As it turns out, an economic system based on attribution -- where those who give more are more empowered -- is significantly more efficient than capitalism while also being stable and fair (_unlike_ capitalism, on both counts), giving it transformative power to elevate the human condition and …
> Trim dependencies

- symex-utils-ts.el
Replace calls to `point-at-bol` and `point-at-eol`. These functions are obsolete since Emacs 29.1.
(**Why**: The freely released, copyright-free work in this repository represents an investment in a better way of doing things called _attribution-based economics_. Attribution-based economics is based on the simple idea that we gain more by giving more, not by holding on to things that, truly, we could only create because we, in our turn, received from others. As it turns out, an economic system based on attribution -- where those who give more are more empowered -- is significantly more efficient than capitalism while also being stable and fair (_unlike_ capitalism, on both counts), giving it transformative power to elevate the human condition and address the problems that face us today …
> Replace calls to obsolete point-at-bol and point-at-eol

- DSL-Docs.rst
- symex-data.el
- symex-dsl.el
- symex-evaluator.el
- symex-primitives-lisp.el
- symex-transformations-lisp.el
- symex-transformations-ts.el
- symex-transformations.el
- symex-traversals.el
Currently, the Symex DSL only has support for motions. We can perform transformations as side effects in traversals (via e.g. `symex--do-while-traversing`) but these side effects are performed at every step of the traversal and cannot be made more fine-grained. This PR adds support for performing arbitrary operations that may be specified in a traversal program at desired points in the traversal. In addition to such general support, it also adds "native" support for core primitives like delete and paste, using which it should be possible to implement a lot of other Symex transformations like emit and capture.
An advantage of doing this now is that, if the DSL uses only a few primitives to implement a large number of features, then we can reuse a lot of this work for Tree Sitter languages …
> Ability to do transformations in the DSL

- abe/attributions.txt
For now, we need the "non-dilutable" attributions for DIA analysts and for Old Abe to be present in the attributions file, marked (via the third, boolean column) as non-dilutable. This requires the remaining attributions already present to be renormalized so that the total comes to 100%.
(**Why**: The freely released, copyright-free work in this repository represents an investment in a better way of doing things called _attribution-based economics_. Attribution-based economics is based on the simple idea that we gain more by giving more, not by holding on to things that, truly, we could only create because we, in our turn, received from others. As it turns out, an economic system based on attribution -- where those who give more are more empowered -- is significantly more efficient than …
> Renormalize attributions to account for DIA and Old Abe allocation

- symex-computations.el
- symex-data.el
- symex-dsl.el
- symex-evaluator.el
- symex-misc.el
- symex-transformations-lisp.el
- symex-transformations.el
- symex-traversals.el
- symex-utils.el
Formerly, side effects could be specified as a mode of evaluation (via a `side-effect` argument to `symex-execute-traversal`). Instead, this PR adds them as just a distinct traversal type, just like `maneuver` or `decision`. This allows us to attach side effects to any traversal or even components of traversals without needing to treat them in a special way. This simplifies the evaluator and gives us more flexibility in general.
I believe this also increases the power of the DSL from regular (finite automaton) to context-free (pushdown automaton), since we can leverage bindings in the ELisp lexical scope to store and update a variable (e.g. to use it as a stack). This is a little bit cheating since the memory representation isn't internal to the Symex language but is part of the host …
> Side effect form

- symex-computations.el
- symex-data.el
- symex-dsl.el
- symex-evaluator.el
- symex-misc.el
- symex-transformations.el
- symex-traversals.el
- symex-ts.el
- symex-utils.el
Improve Symex's computation model and implement "leap branch" much more efficiently by using these traversal computations. We also implement some basic utilities (e.g. `symex-index` and `symex-height`) using traversal computations instead of in an ad hoc way.
Symex's computation model is fold-like in the sense that the results (e.g. moves made) are accumulated in sequence, tree-structured in the sense that failed explorations as part of traversal execution are not included in the final result, and monadic in the sense that the basic "move" object can be lifted into any kind of composable computation (e.g. list concatenation to produce the sequence of moves in the traversal, or vector addition to get the total height traversed, or counting the number of occurrences of a certain term, or …
> Streamline basic computation model

- README.rst
- symex-computations.el
- symex-custom.el
- symex-dsl.el
- symex-evaluator.el
- symex-misc.el
- symex-primitives-lisp.el
- symex-primitives.el
- symex-transformations-lisp.el
- symex-transformations-ts.el
- symex-transformations.el
- symex-ui.el
- symex-utils.el
- symex.el
Some fixes and improvements, including:
- restore emit and capture to working / sensible behavior
- fix deleting and pasting with counts, e.g. `3x` followed by `p` should paste all three expressions (formerly was only pasting the most recently deleted one)
- better handling of surrounding whitespace in deletion
- disable blink cursor in symex state
- other minor improvements and fixes
(**Why**: The freely released, copyright-free work in this repository represents an investment in a better way of doing things called _attribution-based economics_. Attribution-based economics is based on the simple idea that we gain more by giving more, not by holding on to things that, truly, we could only create because we, in our turn, received from others. As it turns out, an economic system based on …
> Fixes in primitives and deletion

- symex-traversals.el
- symex.el
As dicussed in [issue 137](https://github.com/drym-org/symex.el/issues/137) eldoc is no longer working well.
As discussed, the `def-symex-motion` macro has been introduce in order to keep track of the list of available motions.
Those motions can be fed to `eldoc-add-comand` (during `symex-initialize`) in order to restore eldoc behavior.
(**Why**: The freely released, copyright-free work in this repository represents an investment in a better way of doing things called _attribution-based economics_. Attribution-based economics is based on the simple idea that we gain more by giving more, not by holding on to things that, truly, we could only create because we, in our turn, received from others. As it turns out, an economic system based on attribution -- where those who give more are more …
> [Issue 137] Trigger eldoc after symex motions

- symex-interface-elisp.el
In the elisp implementation of `symex-eval-print`, the `forward-sexp` call is not needed (it is done in the `symex-eval-print` before the actual implementation being called)
(**Why**: The freely released, copyright-free work in this repository represents an investment in a better way of doing things called _attribution-based economics_. Attribution-based economics is based on the simple idea that we gain more by giving more, not by holding on to things that, truly, we could only create because we, in our turn, received from others. As it turns out, an economic system based on attribution -- where those who give more are more empowered -- is significantly more efficient than capitalism while also being stable and fair (_unlike_ capitalism, on both counts), giving it transformative power to …
> Remove `forward-sexp` call in `symex-eval-print-elisp`

- symex-primitives-lisp.el
When the point is on the first symex of a string, the `symex-lisp--point-at-start-p` returns nil instead of true.
It brokes the overlay badly.
By adding a clause to `symex-lisp--point-at-start-p` the issue seems to be fixed but maybe I miss something.
https://github.com/drym-org/symex.el/assets/4739483/9bf7f2dc-dbc8-40a7-9a7b-0cd169c9169d
(**Why**: The freely released, copyright-free work in this repository represents an investment in a better way of doing things called _attribution-based economics_. Attribution-based economics is based on the simple idea that we gain more by giving more, not by holding on to things that, truly, we could only create because we, in our turn, received from others. As it turns out, an economic system based on attribution -- where those who give more are more …
> Fix broken overlay when focussing on first symex of a string

- symex-transformations-lisp.el
Fixes #143 
(**Why**: The freely released, copyright-free work in this repository represents an investment in a better way of doing things called _attribution-based economics_. Attribution-based economics is based on the simple idea that we gain more by giving more, not by holding on to things that, truly, we could only create because we, in our turn, received from others. As it turns out, an economic system based on attribution -- where those who give more are more empowered -- is significantly more efficient than capitalism while also being stable and fair (_unlike_ capitalism, on both counts), giving it transformative power to elevate the human condition and address the problems that face us today along with a host of others that have been intractable since the beginning. You can help …
> Save point in comment check during deletion

- symex-primitives-lisp.el
As discussed in [#140](https://github.com/drym-org/symex.el/pull/140), strings are treated as atomic entities in symex.
That being said I think it make sense to select the whole string when entering symex interface from within.
https://github.com/drym-org/symex.el/assets/4739483/8c704afa-76f0-4601-ad7f-f3a2e58db746
(**Why**: The freely released, copyright-free work in this repository represents an investment in a better way of doing things called _attribution-based economics_. Attribution-based economics is based on the simple idea that we gain more by giving more, not by holding on to things that, truly, we could only create because we, in our turn, received from others. As it turns out, an economic system based on attribution -- where those who give more are more empowered -- is …
> Handling entering symex interface from inside a string

- dev/dev-utils.el
- symex-primitives.el
- symex-transformations-ts.el
- symex-transformations.el
- symex-ts.el
- symex.el
Incorporate @polaris64 's updates to migrate to Emacs's built-in treesitter.
**Legend**:
```
[x] = OK
[-] = N/A
[o] = needs design
[ ] = needs fixing
```
**Results**:
```
[x] ("1" digit-argument)
[x] ("2" digit-argument)
[x] ("3" digit-argument)
[x] ("4" digit-argument)
[x] ("5" digit-argument)
[x] ("6" digit-argument)
[x] ("7" digit-argument)
[x] ("8" digit-argument)
[x] ("9" digit-argument)
[x] ("h" symex-go-backward)
[x] ("j" symex-go-down)
[x] ("k" symex-go-up)
[x] ("l" symex-go-forward)
[x] ("gh" backward-char)
[x] ("gj" symex-next-visual-line)
[x] ("gk" symex-previous-visual-line)
[x] ("gl" forward-char)
[x] ("(" symex-create-round)
[x] ("[" symex-create-square)
[ ] (")" symex-wrap-round)
[ ] ("]" symex-wrap-square)
[-] ("C-'" symex-cycle-quote)
[-] ("C-," symex-cycle-unquote)
[-] …
```
> Builtin treesitter

- symex-interface-arc.el
- symex-interface-clojure.el
- symex-interface-common-lisp.el
- symex-interface-elisp.el
- symex-interface-fennel.el
- symex-interface-racket.el
- symex-interface-scheme.el
- symex-interop.el
- symex-lithium.el
- symex-misc.el
- symex-primitives-lisp.el
- symex-primitives.el
- symex-transformations-lisp.el
- symex-transformations.el
- symex.el
Incorporate @devcarbon-com 's work to remove a hard dependency on Evil, from #118 .
There are still some uses of evil that are baked in and which we can't yet put behind a flag. Grepping the project folder for `evil-` shows all such uses of Evil. It should mostly be a matter of replacing each of these functions with built-in Emacs equivalents.
(**Why**: The freely released, copyright-free work in this repository represents an investment in a better way of doing things called _attribution-based economics_. Attribution-based economics is based on the simple idea that we gain more by giving more, not by holding on to things that, truly, we could only create because we, in our turn, received from others. As it turns out, an economic system based on attribution -- where those who give more are …
> Remove dependency on evil
